# Generated by Django 3.0.5 on 2020-09-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(default='', max_length=20)),
                ('cat_desc', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=12)),
                ('gender', models.BooleanField(default='0')),
                ('is_admin', models.BooleanField(default='0')),
            ],
        ),
    ]
