# Generated by Django 3.0.5 on 2020-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_block',
            field=models.BooleanField(default='0'),
        ),
    ]
