# Generated by Django 3.0.5 on 2020-09-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
