# Generated by Django 3.0.5 on 2020-09-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200910_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(),
        ),
    ]
