# Generated by Django 3.0.5 on 2020-09-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200912_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_image', models.URLField()),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
    ]
