# Generated by Django 3.0.5 on 2020-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200928_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(),
        ),
    ]
