# Generated by Django 3.0.5 on 2020-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.URLField(default='/website/product_Images/Headlight.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(),
        ),
    ]
