# Generated by Django 3.1.2 on 2020-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20201031_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bil_pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_add',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.URLField(default='/web', null=True),
        ),
    ]
