# Generated by Django 3.1.2 on 2020-11-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20201102_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=255)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
    ]
