# Generated by Django 3.1.2 on 2020-11-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20201121_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedback1',
        ),
    ]
