# Generated by Django 3.1.2 on 2020-12-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20201130_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='order1',
        ),
    ]
