# Generated by Django 3.1.2 on 2020-12-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20201201_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='order_status',
            field=models.IntegerField(default='2'),
        ),
    ]
